---

base_locale: en
locales: [en, fr]

ignore_unused:
  - decidim.components.socio_demographic_authorization_handler.name
  - decidim.authorization_handlers.socio_demographic_authorization_handler.name
  - decidim.authorization_handlers.socio_demographic_authorization_handler.explanation
  - decidim.verifications.authorizations.first_login.actions.socio_demographic_authorization_handler

ignore_missing:
  - decidim.participatory_processes.scopes.global
